"""Initial migration.

Revision ID: 7dae8097259d
Revises: 
Create Date: 2023-03-10 13:52:32.331108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dae8097259d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['categorey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('myserveraddress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('myserveraddress',
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('posts')
    op.drop_table('categorey')
    # ### end Alembic commands ###
